services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: mini_rag_postgres
    environment:
      POSTGRES_DB: mini_rag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: mini_rag_redis
    ports:
      - "6379:6379"
